#/* SPDX-License-Identifier: Apache-2.0 */
#/* Copyright (c) 2012-2024 Applied Communication Sciences
# * (now Peraton Labs Inc.)
# *
# * This software was developed in work supported by the following U.S.
# * Government contracts:
# *
# * HR0011-20-C-0160 HR0011-16-C-0061
# *
# *
# * Any opinions, findings and conclusions or recommendations expressed in
# * this material are those of the author(s) and do not necessarily reflect
# * the views, either expressed or implied, of the U.S. Government.
# *
# * DoD Distribution Statement A
# * Approved for Public Release, Distribution Unlimited
# *
# * DISTAR 40011, cleared July 24, 2024
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://www.apache.org/licenses/LICENSE-2.0
# */

services:
  attacker:
    image: "vanilla/base"
    volumes:
        - ${DIST}:/DIST
    working_dir: /DIST
    container_name: "attacker"
    hostname: "attacker"
    privileged: "true"
    stdin_open: "true"
    tty: "true"
    command: /usr/bin/bash -c "ip route add 192.168.2.0/24 via 192.168.1.2 && ip route add 10.0.0.0/24 via 192.168.1.2 && /usr/bin/bash"
    networks:
      src-lan:
        ipv4_address: 192.168.1.1

  src-mec:
    image: "vanilla/base"
    volumes:
        - ${DIST}:/DIST
    working_dir: /DIST
    container_name: "src-mec"
    hostname: "src-mec"
    privileged: "true"
    stdin_open: "true"
    tty: "true"
    command: /usr/bin/bash -c "ip route add 192.168.2.0/24 via 10.0.0.2 && echo 0 | tee /proc/sys/net/ipv4/conf/all/rp_filter && echo 0 | tee /proc/sys/net/ipv4/conf/default/rp_filter && /usr/bin/bash"
    networks:
      mgmt:
        ipv4_address: 172.20.30.11
      core:
        ipv4_address: 10.0.0.1
      src-lan:
        ipv4_address: 192.168.1.2

  tgt-mec:
    image: "vanilla/base"
    volumes:
        - ${DIST}:/DIST
    working_dir: /DIST
    container_name: "tgt-mec"
    hostname: "tgt-mec"
    privileged: "true"
    stdin_open: "true"
    tty: "true"
    command: /usr/bin/bash -c "ip route add 192.168.1.0/24 via 10.0.0.1 && echo 0 | tee /proc/sys/net/ipv4/conf/all/rp_filter && echo 0 | tee /proc/sys/net/ipv4/conf/default/rp_filter && /usr/bin/bash"
    networks:
      mgmt:
        ipv4_address: 172.20.30.12
      core:
        ipv4_address: 10.0.0.2
      tgt-lan:
        ipv4_address: 192.168.2.2

  target:
    image: "vanilla/base"
    volumes:
        - ${DIST}:/DIST
    working_dir: /DIST
    container_name: "target"
    hostname: "target"
    privileged: "true"
    stdin_open: "true"
    tty: "true"
    command: /usr/bin/bash -c "ip route add 192.168.1.0/24 via 192.168.2.2 && ip route add 10.0.0.0/24 via 192.168.2.2 && ip route del default && ip route add default via 192.168.2.2 && sysctl -w net.ipv4.icmp_ratelimit=0 && echo 0 | tee /proc/sys/net/ipv4/conf/all/rp_filter && echo 0 | tee /proc/sys/net/ipv4/conf/default/rp_filter && /usr/bin/bash"
    networks:
      tgt-lan:
        ipv4_address: 192.168.2.1

networks:
  src-lan:
    name: "src-lan"
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.254

  mgmt:
    name: "mgmt"
    ipam:
      config:
        - subnet: 172.20.30.0/24
          ip_range: 172.20.30.0/24
          gateway: 172.20.30.254

  core:
    name: "core"
    ipam:
      config:
        - subnet: 10.0.0.0/24
          ip_range: 10.0.0.0/24
          gateway: 10.0.0.254

  tgt-lan:
    name: "tgt-lan"
    ipam:
      config:
        - subnet: 192.168.2.0/24
          ip_range: 192.168.2.0/24
          gateway: 192.168.2.254
